### ISSUE TITLE
Zabbix plugin should also receive the NSR from NFVO

### ISSUE THREAD

**Issue by gc4rella** [openbaton/zabbix-plugin#6]
And should create specific user metrics which are contained in any policies (fault managent and autoscaling)

**Comment by marcellom** [comment]
In order to receive the NSR, the Zabbix plugin could register, at startup, to the NFVO for the event INSTANTIATE_FINISH. Then, it can create the user metrics (if they don't already exist) contained in the policies once it gets the new NSR. Is it ok?

**Comment by gc4rella** [comment]
yes

**Comment by marcellom** [comment]
**Answer:**
At the moment, the zabbix-plugin uses the plugin mechanism, as openstack-plugin. Making it a service, like FMS and ASE, will change the code of the FMS and ASE too, because they use the zabbix-plugin as a plugin.

**More detailed explaination:**
The zabbix-plugin is basically a class, as other plugins, so it is not an active component that can register to the NFVO and listen to events. What makes the zabbix-plugin an active process is the plugin-sdk which is a thread that listens on RabbitMQ, invokes methods of the zabbix-plugin class and returns the result. Enabling the zabbix-plugin to register to the NFVO and to receive NSRs, requires, IMHO, switching the zabbix-plugin from a plugin to a component (spring-boot app) like FMS and ASE.

@gc4rella can I close the issue?

**Comment by lorenzotomasini** [comment]
I think we should think about a more complex monitoring module. The plugin is fine like it is for the purpose it was meant to, but since the requirements we are now increasing, i suggest to extend the orchestrator including an optional monitoring module that will satisfy more complex requirements and will make use of the monitoring plugin

**Comment by marcellom** [comment]
I am going to close this issue soon if no one replies.
